package com.jme3.handskeleton;

import org.lwjgl.openxr.EXTHandTracking;

public enum HandJoint {
    PALM_EXT(EXTHandTracking.XR_HAND_JOINT_PALM_EXT),
    WRIST_EXT(EXTHandTracking.XR_HAND_JOINT_WRIST_EXT),
    THUMB_METACARPAL_EXT(EXTHandTracking.XR_HAND_JOINT_THUMB_METACARPAL_EXT),
    THUMB_PROXIMAL_EXT(EXTHandTracking.XR_HAND_JOINT_THUMB_PROXIMAL_EXT),
    THUMB_DISTAL_EXT(EXTHandTracking.XR_HAND_JOINT_THUMB_DISTAL_EXT),
    THUMB_TIP_EXT(EXTHandTracking.XR_HAND_JOINT_THUMB_TIP_EXT),
    INDEX_METACARPAL_EXT(EXTHandTracking.XR_HAND_JOINT_INDEX_METACARPAL_EXT),
    INDEX_PROXIMAL_EXT(EXTHandTracking.XR_HAND_JOINT_INDEX_PROXIMAL_EXT),
    INDEX_INTERMEDIATE_EXT(EXTHandTracking.XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT),
    INDEX_DISTAL_EXT(EXTHandTracking.XR_HAND_JOINT_INDEX_DISTAL_EXT),
    INDEX_TIP_EXT(EXTHandTracking.XR_HAND_JOINT_INDEX_TIP_EXT),
    MIDDLE_METACARPAL_EXT(EXTHandTracking.XR_HAND_JOINT_MIDDLE_METACARPAL_EXT),
    MIDDLE_PROXIMAL_EXT(EXTHandTracking.XR_HAND_JOINT_MIDDLE_PROXIMAL_EXT),
    MIDDLE_INTERMEDIATE_EXT(EXTHandTracking.XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT),
    MIDDLE_DISTAL_EXT(EXTHandTracking.XR_HAND_JOINT_MIDDLE_DISTAL_EXT),
    MIDDLE_TIP_EXT(EXTHandTracking.XR_HAND_JOINT_MIDDLE_TIP_EXT),
    RING_METACARPAL_EXT(EXTHandTracking.XR_HAND_JOINT_RING_METACARPAL_EXT),
    RING_PROXIMAL_EXT(EXTHandTracking.XR_HAND_JOINT_RING_PROXIMAL_EXT),
    RING_INTERMEDIATE_EXT(EXTHandTracking.XR_HAND_JOINT_RING_INTERMEDIATE_EXT),
    RING_DISTAL_EXT(EXTHandTracking.XR_HAND_JOINT_RING_DISTAL_EXT),
    RING_TIP_EXT(EXTHandTracking.XR_HAND_JOINT_RING_TIP_EXT),
    LITTLE_METACARPAL_EXT(EXTHandTracking.XR_HAND_JOINT_LITTLE_METACARPAL_EXT),
    LITTLE_PROXIMAL_EXT(EXTHandTracking.XR_HAND_JOINT_LITTLE_PROXIMAL_EXT),
    LITTLE_INTERMEDIATE_EXT(EXTHandTracking.XR_HAND_JOINT_LITTLE_INTERMEDIATE_EXT),
    LITTLE_DISTAL_EXT(EXTHandTracking.XR_HAND_JOINT_LITTLE_DISTAL_EXT),
    LITTLE_TIP_EXT(EXTHandTracking.XR_HAND_JOINT_LITTLE_TIP_EXT);

    private final int jointIndex;

    HandJoint(int jointIndex) {
        this.jointIndex = jointIndex;
    }

    public int getJointIndex() {
        return jointIndex;
    }
}